const emojiData = {
    smileys: [
        { emoji: '😀', tags: ['smile', 'happy', 'grin'] },
        { emoji: '😃', tags: ['smile', 'happy', 'joy'] },
        { emoji: '😄', tags: ['smile', 'happy', 'laugh'] },
        { emoji: '😁', tags: ['grin', 'teeth', 'happy'] },
        { emoji: '😆', tags: ['laugh', 'grin', 'happy'] },
        { emoji: '😅', tags: ['sweat', 'nervous', 'smile'] },
        { emoji: '🤣', tags: ['laugh', 'funny', 'tears'] },
        { emoji: '😂', tags: ['tears', 'laugh', 'funny'] },
        { emoji: '🙂', tags: ['smile', 'calm', 'happy'] },
        { emoji: '🙃', tags: ['upside down', 'weird', 'fun'] },
        { emoji: '🫠', tags: ['melt', 'melting', 'heat'] },
        { emoji: '😉', tags: ['wink', 'happy', 'smile'] },
        { emoji: '😊', tags: ['blush', 'happy', 'smile'] },
        { emoji: '😇', tags: ['angel', 'innocent', 'halo'] },
        { emoji: '🥰', tags: ['love', 'heart', 'affection'] },
        { emoji: '😍', tags: ['love', 'heart', 'eyes'] },
        { emoji: '🤩', tags: ['star', 'amazed', 'wow'] },
        { emoji: '😘', tags: ['kiss', 'love', 'heart'] },
        { emoji: '😗', tags: ['kiss', 'affection', 'love'] },
        { emoji: '☺️', tags: ['smile', 'happy', 'blush'] },
        { emoji: '😚', tags: ['kiss', 'love', 'affection'] },
        { emoji: '😙', tags: ['kiss', 'smile', 'love'] },
        { emoji: '🥲', tags: ['tears', 'smile', 'relief'] },
        { emoji: '😋', tags: ['yum', 'food', 'taste'] },
        { emoji: '😛', tags: ['tongue', 'playful', 'silly'] },
        { emoji: '😜', tags: ['wink', 'playful', 'tongue'] },
        { emoji: '🤪', tags: ['crazy', 'funny', 'playful'] },
        { emoji: '😝', tags: ['tongue', 'silly', 'playful'] },
        { emoji: '🤑', tags: ['money', 'rich', 'tongue'] },
        { emoji: '🤗', tags: ['hug', 'affection', 'care'] },
        { emoji: '🤭', tags: ['oops', 'giggle', 'embarrassed'] },
        { emoji: '🫢', tags: ['surprised', 'shock', 'gasp'] },
        { emoji: '🫣', tags: ['peeking', 'shy', 'hidden'] },
        { emoji: '🤫', tags: ['shh', 'quiet', 'secret'] },
        { emoji: '🤔', tags: ['thinking', 'pensive', 'question'] },
        { emoji: '🫡', tags: ['salute', 'respect', 'acknowledge'] },
        { emoji: '🤐', tags: ['silence', 'zip', 'secret'] },
        { emoji: '🤨', tags: ['raised eyebrow', 'skeptical', 'confused'] },
        { emoji: '😐', tags: ['neutral', 'indifferent', 'meh'] },
        { emoji: '😑', tags: ['expressionless', 'blank', 'meh'] },
        { emoji: '😶', tags: ['silent', 'no mouth', 'mute'] },
        { emoji: '🫥', tags: ['invisible', 'vanish', 'blur'] },
        { emoji: '😶‍🌫️', tags: ['foggy', 'clouded', 'confusion'] },
        { emoji: '😏', tags: ['smirk', 'smug', 'confident'] },
        { emoji: '😒', tags: ['unimpressed', 'annoyed', 'meh'] },
        { emoji: '🙄', tags: ['eyeroll', 'annoyed', 'sassy'] },
        { emoji: '😬', tags: ['grimace', 'awkward', 'nervous'] },
        { emoji: '😮‍💨', tags: ['relieved', 'sigh', 'breath'] },
        { emoji: '🤥', tags: ['lie', 'nose', 'liar'] },
        { emoji: '🫨', tags: ['shaking', 'shock', 'rattle'] },
        { emoji: '😌', tags: ['relaxed', 'content', 'satisfied'] },
        { emoji: '😔', tags: ['sad', 'disappointed', 'upset'] },
        { emoji: '😪', tags: ['sleepy', 'tired', 'zzz'] },
        { emoji: '🤤', tags: ['drool', 'hungry', 'sleepy'] },
        { emoji: '😴', tags: ['sleep', 'zzz', 'rest'] },
        { emoji: '😷', tags: ['sick', 'mask', 'ill'] },
        { emoji: '🤒', tags: ['fever', 'sick', 'ill'] },
        { emoji: '🤕', tags: ['injured', 'hurt', 'bandage'] },
        { emoji: '🤢', tags: ['nausea', 'sick', 'vomit'] },
        { emoji: '🤮', tags: ['vomit', 'sick', 'disgust'] },
        { emoji: '🤧', tags: ['sneeze', 'cold', 'sick'] },
        { emoji: '🥵', tags: ['hot', 'heat', 'sweating'] },
        { emoji: '🥶', tags: ['cold', 'freezing', 'shivering'] },
        { emoji: '🥴', tags: ['woozy', 'drunk', 'dizzy'] },
        { emoji: '😵', tags: ['dizzy', 'woozy', 'disoriented'] },
        { emoji: '😵‍💫', tags: ['dizzy', 'spinning', 'confusion'] },
        { emoji: '🤯', tags: ['mind blown', 'shock', 'surprised'] },
        { emoji: '🤠', tags: ['cowboy', 'hat', 'wild'] },
        { emoji: '🥳', tags: ['party', 'celebrate', 'fun'] },
        { emoji: '🥸', tags: ['disguise', 'funny', 'glasses'] },
        { emoji: '😎', tags: ['cool', 'sunglasses', 'style'] },
        { emoji: '🤓', tags: ['nerd', 'smart', 'glasses'] },
        { emoji: '🧐', tags: ['serious', 'monocle', 'curious'] },
        { emoji: '😕', tags: ['confused', 'puzzled', 'uncertain'] },
        { emoji: '😟', tags: ['worried', 'concerned', 'sad'] },
        { emoji: '🙁', tags: ['frown', 'sad', 'upset'] },
        { emoji: '☹️', tags: ['frown', 'sad', 'upset'] },
        { emoji: '😮', tags: ['surprised', 'shock', 'wow'] },
        { emoji: '😯', tags: ['surprise', 'shocked', 'gasp'] },
        { emoji: '😲', tags: ['shock', 'surprised', 'gasp'] },
        { emoji: '😳', tags: ['embarrassed', 'blush', 'shock'] },
        { emoji: '🥺', tags: ['puppy eyes', 'begging', 'sad'] },
        { emoji: '😦', tags: ['frown', 'upset', 'disappointed'] },
        { emoji: '😧', tags: ['anguish', 'shock', 'worry'] },
        { emoji: '😨', tags: ['fear', 'scared', 'shock'] },
        { emoji: '😰', tags: ['sweat', 'fear', 'nervous'] },
        { emoji: '😥', tags: ['sweat', 'relief', 'disappointment'] },
        { emoji: '😢', tags: ['cry', 'sad', 'tear'] },
        { emoji: '😭', tags: ['crying', 'tears', 'sad'] },
        { emoji: '😱', tags: ['scream', 'fear', 'shock'] },
        { emoji: '😖', tags: ['anguish', 'frustration', 'upset'] },
        { emoji: '😣', tags: ['frustration', 'disappointed', 'upset'] },
        { emoji: '😞', tags: ['disappointed', 'sad', 'upset'] },
        { emoji: '😓', tags: ['sweat', 'disappointment', 'tired'] },
        { emoji: '😩', tags: ['tired', 'exhausted', 'upset'] },
        { emoji: '😫', tags: ['tired', 'frustrated', 'upset'] },
        { emoji: '🥱', tags: ['yawn', 'tired', 'sleepy'] },
        { emoji: '😤', tags: ['triumph', 'proud', 'angry'] },
        { emoji: '😡', tags: ['angry', 'mad', 'upset'] },
        { emoji: '😠', tags: ['angry', 'mad', 'frustrated'] },
        { emoji: '🤬', tags: ['swearing', 'angry', 'mad'] },
        { emoji: '😈', tags: ['devil', 'smiling', 'evil'] },
        { emoji: '👿', tags: ['angry', 'devil', 'evil'] },
        { emoji: '💀', tags: ['skull', 'death', 'dead'] },
        { emoji: '☠️', tags: ['skull', 'bones', 'danger'] },
        { emoji: '💩', tags: ['poop', 'shit', 'funny'] },
        { emoji: '🤡', tags: ['clown', 'funny', 'creepy'] },
        { emoji: '👹', tags: ['ogre', 'monster', 'angry'] },
        { emoji: '👺', tags: ['goblin', 'angry', 'monster'] },
        { emoji: '👻', tags: ['ghost', 'spooky', 'halloween'] },
        { emoji: '👽', tags: ['alien', 'ufo', 'space'] },
        { emoji: '👾', tags: ['alien', 'video game', 'monster'] },
        { emoji: '🤖', tags: ['robot', 'tech', 'future'] },
        { emoji: '😺', tags: ['smile', 'cat', 'happy'] },
        { emoji: '😸', tags: ['smile', 'cat', 'joy'] },
        { emoji: '😹', tags: ['laugh', 'cat', 'funny'] },
        { emoji: '😻', tags: ['love', 'cat', 'heart'] },
        { emoji: '😼', tags: ['smirk', 'cat', 'sly'] },
        { emoji: '😽', tags: ['kiss', 'cat', 'affection'] },
        { emoji: '🙀', tags: ['shock', 'cat', 'surprised'] },
        { emoji: '😿', tags: ['cry', 'cat', 'sad'] },
        { emoji: '😾', tags: ['angry', 'cat', 'frustrated'] },
        { emoji: '🙈', tags: ['monkey', 'see no evil', 'hidden'] },
        { emoji: '🙉', tags: ['monkey', 'hear no evil', 'cover ears'] },
        { emoji: '🙊', tags: ['monkey', 'speak no evil', 'cover mouth'] },
        { emoji: '💋', tags: ['kiss', 'lips', 'love'] },
        { emoji: '💯', tags: ['100', 'perfect', 'score'] },
        { emoji: '💢', tags: ['anger', 'mad', 'frustrated'] },
        { emoji: '💥', tags: ['explosion', 'boom', 'impact'] },
        { emoji: '💫', tags: ['dizzy', 'stars', 'spin'] },
        { emoji: '💦', tags: ['sweat', 'water', 'drops'] },
        { emoji: '💨', tags: ['wind', 'fast', 'motion'] },
        { emoji: '🕳️', tags: ['hole', 'void', 'black'] },
        { emoji: '💤', tags: ['zzz', 'sleep', 'tired'] },
        { emoji: '👋', tags: ['wave', 'goodbye', 'hello'] },
        { emoji: '🤚', tags: ['raised hand', 'stop', 'hi'] },
        { emoji: '🖐️', tags: ['hand', 'high five', 'palm'] },
        { emoji: '✋', tags: ['stop', 'hand', 'hi'] },
        { emoji: '🖖', tags: ['vulcan', 'live long', 'hand'] },
        { emoji: '👌', tags: ['okay', 'hand', 'perfect'] },
        { emoji: '🤌', tags: ['pinched fingers', 'italian', 'gesture'] },
        { emoji: '🤏', tags: ['pinch', 'small', 'hand'] },
        { emoji: '✌️', tags: ['peace', 'victory', 'hand'] },
        { emoji: '🤞', tags: ['cross fingers', 'luck', 'hope'] },
        { emoji: '🤟', tags: ['love', 'sign', 'gesture'] },
        { emoji: '🤘', tags: ['rock', 'sign', 'gesture'] },
        { emoji: '🤙', tags: ['call me', 'hang loose', 'hand'] },
        { emoji: '👈', tags: ['left', 'point', 'hand'] },
        { emoji: '👉', tags: ['right', 'point', 'hand'] },
        { emoji: '👆', tags: ['up', 'point', 'hand'] },
        { emoji: '🖕', tags: ['middle finger', 'rude', 'gesture'] },
        { emoji: '👇', tags: ['down', 'point', 'hand'] },
        { emoji: '☝️', tags: ['up', 'point', 'hand'] },
        { emoji: '👍', tags: ['thumbs up', 'approve', 'good'] },
        { emoji: '👎', tags: ['thumbs down', 'disapprove', 'bad'] },
        { emoji: '✊', tags: ['fist', 'solidarity', 'power'] },
        { emoji: '👊', tags: ['punch', 'fist', 'attack'] },
        { emoji: '👏', tags: ['clap', 'applause', 'praise'] },
        { emoji: '🙌', tags: ['raised hands', 'celebrate', 'praise'] },
        { emoji: '👐', tags: ['open hands', 'offering', 'give'] },
        { emoji: '🤲', tags: ['hands together', 'offering', 'give'] },
        { emoji: '🤝', tags: ['handshake', 'agreement', 'deal'] },
        { emoji: '🙏', tags: ['prayer', 'please', 'thank you'] },
        { emoji: '✍️', tags: ['writing', 'pen', 'hand'] },
        { emoji: '💅', tags: ['nails', 'manicure', 'hand'] },
        { emoji: '🤳', tags: ['selfie', 'phone', 'camera'] },
        { emoji: '💪', tags: ['muscle', 'strong', 'arm'] },
        { emoji: '🦾', tags: ['robot arm', 'prosthetic', 'strong'] },
        { emoji: '🦿', tags: ['prosthetic leg', 'robot', 'strong'] },
        { emoji: '🦵', tags: ['leg', 'strong', 'knee'] },
        { emoji: '🦶', tags: ['foot', 'walk', 'step'] },
        { emoji: '👂', tags: ['ear', 'hear', 'listen'] },
        { emoji: '🦻', tags: ['hearing aid', 'ear', 'deaf'] },
        { emoji: '👃', tags: ['nose', 'smell', 'sniff'] },
        { emoji: '🧠', tags: ['brain', 'think', 'intelligence'] },
        { emoji: '🫀', tags: ['heart', 'organ', 'anatomy'] },
        { emoji: '🫁', tags: ['lungs', 'breath', 'anatomy'] },
        { emoji: '🦷', tags: ['tooth', 'dentist', 'bite'] },
        { emoji: '🦴', tags: ['bone', 'skeleton', 'structure'] },
        { emoji: '👀', tags: ['eyes', 'look', 'see'] },
        { emoji: '👁️', tags: ['eye', 'look', 'vision'] },
        { emoji: '👅', tags: ['tongue', 'taste', 'lick'] },
        { emoji: '👄', tags: ['mouth', 'lip', 'kiss'] },
        { emoji: '🫦', tags: ['biting lip', 'nervous', 'flirt'] }   
    ],
    
    animals: [
        { emoji: '🐵', tags: ['monkey', 'animal', 'primate'] },
        { emoji: '🐒', tags: ['monkey', 'animal', 'swing'] },
        { emoji: '🦍', tags: ['gorilla', 'animal', 'primate'] },
        { emoji: '🦧', tags: ['orangutan', 'animal', 'primate'] },
        { emoji: '🐶', tags: ['dog', 'puppy', 'pet'] },
        { emoji: '🐕', tags: ['dog', 'animal', 'pet'] },
        { emoji: '🦮', tags: ['guide dog', 'animal', 'blind'] },
        { emoji: '🐕‍🦺', tags: ['service dog', 'animal', 'disabled'] },
        { emoji: '🐩', tags: ['poodle', 'dog', 'pet'] },
        { emoji: '🐺', tags: ['wolf', 'animal', 'wild'] },
        { emoji: '🦊', tags: ['fox', 'animal', 'wild'] },
        { emoji: '🦝', tags: ['raccoon', 'animal', 'trash'] },
        { emoji: '🐱', tags: ['cat', 'pet', 'kitten'] },
        { emoji: '🐈', tags: ['cat', 'animal', 'pet'] },
        { emoji: '🐈‍⬛', tags: ['black cat', 'animal', 'witch'] },
        { emoji: '🦁', tags: ['lion', 'animal', 'king'] },
        { emoji: '🐯', tags: ['tiger', 'animal', 'fierce'] },
        { emoji: '🐅', tags: ['tiger', 'animal', 'stripe'] },
        { emoji: '🐆', tags: ['leopard', 'animal', 'spots'] },
        { emoji: '🐴', tags: ['horse', 'animal', 'ride'] },
        { emoji: '🫎', tags: ['moose', 'animal', 'wild'] },
        { emoji: '🫏', tags: ['donkey', 'animal', 'farm'] },
        { emoji: '🐎', tags: ['racehorse', 'animal', 'fast'] },
        { emoji: '🦄', tags: ['unicorn', 'myth', 'fantasy'] },
        { emoji: '🦓', tags: ['zebra', 'animal', 'stripe'] },
        { emoji: '🦌', tags: ['deer', 'animal', 'wild'] },
        { emoji: '🦬', tags: ['bison', 'animal', 'wild'] },
        { emoji: '🐮', tags: ['cow', 'animal', 'farm'] },
        { emoji: '🐂', tags: ['ox', 'animal', 'bull'] },
        { emoji: '🐃', tags: ['water buffalo', 'animal', 'farm'] },
        { emoji: '🐄', tags: ['cow', 'animal', 'milk'] },
        { emoji: '🐷', tags: ['pig', 'animal', 'farm'] },
        { emoji: '🐖', tags: ['pig', 'animal', 'meat'] },
        { emoji: '🐗', tags: ['boar', 'animal', 'wild'] },
        { emoji: '🐽', tags: ['pig nose', 'snout', 'animal'] },
        { emoji: '🐏', tags: ['ram', 'animal', 'horn'] },
        { emoji: '🐑', tags: ['sheep', 'animal', 'wool'] },
        { emoji: '🐐', tags: ['goat', 'animal', 'horn'] },
        { emoji: '🐪', tags: ['camel', 'animal', 'desert'] },
        { emoji: '🐫', tags: ['camel', 'desert', 'hump'] },
        { emoji: '🦙', tags: ['llama', 'animal', 'wool'] },
        { emoji: '🦒', tags: ['giraffe', 'animal', 'tall'] },
        { emoji: '🐘', tags: ['elephant', 'animal', 'big'] },
        { emoji: '🦣', tags: ['mammoth', 'animal', 'extinct'] },
        { emoji: '🦏', tags: ['rhinoceros', 'animal', 'horn'] },
        { emoji: '🦛', tags: ['hippopotamus', 'animal', 'river'] },
        { emoji: '🐭', tags: ['mouse', 'animal', 'rodent'] },
        { emoji: '🐁', tags: ['mouse', 'animal', 'rodent'] },
        { emoji: '🐀', tags: ['rat', 'animal', 'rodent'] },
        { emoji: '🐹', tags: ['hamster', 'animal', 'pet'] },
        { emoji: '🐰', tags: ['rabbit', 'animal', 'bunny'] },
        { emoji: '🐇', tags: ['rabbit', 'animal', 'hop'] },
        { emoji: '🐿️', tags: ['squirrel', 'animal', 'forest'] },
        { emoji: '🦫', tags: ['beaver', 'animal', 'dam'] },
        { emoji: '🦔', tags: ['hedgehog', 'animal', 'spiky'] },
        { emoji: '🦇', tags: ['bat', 'animal', 'vampire'] },
        { emoji: '🐻', tags: ['bear', 'animal', 'wild'] },
        { emoji: '🐻‍❄️', tags: ['polar bear', 'animal', 'ice'] },
        { emoji: '🐨', tags: ['koala', 'animal', 'tree'] },
        { emoji: '🐼', tags: ['panda', 'animal', 'bamboo'] },
        { emoji: '🦥', tags: ['sloth', 'animal', 'slow'] },
        { emoji: '🦦', tags: ['otter', 'animal', 'water'] },
        { emoji: '🦨', tags: ['skunk', 'animal', 'smell'] },
        { emoji: '🦘', tags: ['kangaroo', 'animal', 'jump'] },
        { emoji: '🦡', tags: ['badger', 'animal', 'wild'] },
        { emoji: '🐾', tags: ['paw prints', 'tracks', 'animal'] }
    ],
    
    food: [
        { emoji: '🍇', tags: ['grapes', 'fruit', 'food'] },
        { emoji: '🍈', tags: ['melon', 'fruit', 'food'] },
        { emoji: '🍉', tags: ['watermelon', 'fruit', 'food'] },
        { emoji: '🍊', tags: ['orange', 'fruit', 'food'] },
        { emoji: '🍋', tags: ['lemon', 'fruit', 'sour'] },
        { emoji: '🍌', tags: ['banana', 'fruit', 'food'] },
        { emoji: '🍍', tags: ['pineapple', 'fruit', 'tropical'] },
        { emoji: '🥭', tags: ['mango', 'fruit', 'tropical'] },
        { emoji: '🍎', tags: ['apple', 'fruit', 'red'] },
        { emoji: '🍏', tags: ['green apple', 'fruit', 'food'] },
        { emoji: '🍐', tags: ['pear', 'fruit', 'food'] },
        { emoji: '🍑', tags: ['peach', 'fruit', 'food'] },
        { emoji: '🍒', tags: ['cherry', 'fruit', 'red'] },
        { emoji: '🍓', tags: ['strawberry', 'fruit', 'berry'] },
        { emoji: '🫐', tags: ['blueberry', 'fruit', 'berry'] },
        { emoji: '🥝', tags: ['kiwi', 'fruit', 'food'] },
        { emoji: '🍅', tags: ['tomato', 'fruit', 'vegetable'] },
        { emoji: '🫒', tags: ['olive', 'fruit', 'food'] },
        { emoji: '🥥', tags: ['coconut', 'fruit', 'food'] },
        { emoji: '🥑', tags: ['avocado', 'fruit', 'food'] },
        { emoji: '🍆', tags: ['eggplant', 'vegetable', 'food'] },
        { emoji: '🥔', tags: ['potato', 'vegetable', 'food'] },
        { emoji: '🥕', tags: ['carrot', 'vegetable', 'food'] },
        { emoji: '🌽', tags: ['corn', 'vegetable', 'food'] },
        { emoji: '🌶️', tags: ['chili pepper', 'vegetable', 'spicy'] }
    ],
    
    activities: [
        { emoji: '🎃', tags: ['pumpkin', 'halloween', 'jack o lantern'] },
        { emoji: '🎄', tags: ['christmas', 'tree', 'holiday'] },
        { emoji: '🎆', tags: ['fireworks', 'celebrate', 'explosion'] },
        { emoji: '🎇', tags: ['sparkler', 'celebrate', 'light'] },
        { emoji: '🧨', tags: ['firecracker', 'explosive', 'new year'] },
        { emoji: '✨', tags: ['sparkles', 'shine', 'stars'] },
        { emoji: '🎈', tags: ['balloon', 'party', 'celebration'] },
        { emoji: '🎉', tags: ['party popper', 'celebrate', 'fun'] },
        { emoji: '🎊', tags: ['confetti ball', 'celebrate', 'party'] },
        { emoji: '🎋', tags: ['tanabata', 'tree', 'wishes'] },
        { emoji: '🎍', tags: ['pine decoration', 'new year', 'celebrate'] },
        { emoji: '🎎', tags: ['dolls', 'celebrate', 'japan'] },
        { emoji: '🎏', tags: ['carp streamer', 'japan', 'celebration'] },
        { emoji: '🎐', tags: ['wind chime', 'summer', 'japan'] },
        { emoji: '🎑', tags: ['moon viewing', 'celebrate', 'japan'] },
        { emoji: '🧧', tags: ['red envelope', 'money', 'chinese new year'] },
        { emoji: '🎀', tags: ['ribbon', 'bow', 'gift'] },
        { emoji: '🎁', tags: ['present', 'gift', 'celebrate'] },
        { emoji: '🎗️', tags: ['ribbon', 'awareness', 'support'] },
        { emoji: '🎟️', tags: ['ticket', 'admit', 'event'] },
        { emoji: '🎫', tags: ['ticket', 'admission', 'event'] },
        { emoji: '🎖️', tags: ['medal', 'award', 'achievement'] },
        { emoji: '🏆', tags: ['trophy', 'award', 'winner'] },
        { emoji: '🏅', tags: ['medal', 'award', 'winner'] },
        { emoji: '🥇', tags: ['first place', 'gold', 'winner'] },
        { emoji: '🥈', tags: ['second place', 'silver', 'winner'] },
        { emoji: '🥉', tags: ['third place', 'bronze', 'winner'] },
        { emoji: '⚽', tags: ['soccer', 'sports', 'football'] },
        { emoji: '⚾', tags: ['baseball', 'sports', 'game'] },
        { emoji: '🥎', tags: ['softball', 'sports', 'game'] },
        { emoji: '🏀', tags: ['basketball', 'sports', 'game'] },
        { emoji: '🏐', tags: ['volleyball', 'sports', 'game'] },
        { emoji: '🏈', tags: ['football', 'sports', 'game'] },
        { emoji: '🏉', tags: ['rugby', 'sports', 'game'] },
        { emoji: '🎾', tags: ['tennis', 'sports', 'game'] },
        { emoji: '🥏', tags: ['frisbee', 'sports', 'game'] },
        { emoji: '🎳', tags: ['bowling', 'sports', 'game'] },
        { emoji: '🏏', tags: ['cricket', 'sports', 'game'] },
        { emoji: '🏑', tags: ['hockey', 'sports', 'game'] },
        { emoji: '🏒', tags: ['ice hockey', 'sports', 'game'] },
        { emoji: '🥍', tags: ['lacrosse', 'sports', 'game'] },
        { emoji: '🏓', tags: ['ping pong', 'sports', 'game'] },
        { emoji: '🏸', tags: ['badminton', 'sports', 'game'] },
        { emoji: '🥊', tags: ['boxing', 'sports', 'fight'] },
        { emoji: '🥋', tags: ['martial arts', 'karate', 'judo'] },
        { emoji: '🥅', tags: ['goal', 'net', 'sports'] },
        { emoji: '⛳', tags: ['golf', 'sports', 'game'] },
        { emoji: '⛸️', tags: ['skate', 'sports', 'ice'] },
        { emoji: '🎣', tags: ['fishing', 'sports', 'outdoors'] },
        { emoji: '🤿', tags: ['diving', 'sports', 'water'] },
        { emoji: '🎽', tags: ['running', 'sports', 'race'] },
        { emoji: '🎿', tags: ['ski', 'sports', 'winter'] },
        { emoji: '🛷', tags: ['sled', 'sports', 'winter'] },
        { emoji: '🥌', tags: ['curling', 'sports', 'winter'] },
        { emoji: '🎯', tags: ['dart', 'target', 'game'] },
        { emoji: '🪀', tags: ['yoyo', 'toy', 'game'] },
        { emoji: '🪁', tags: ['kite', 'toy', 'game'] },
        { emoji: '🔫', tags: ['water gun', 'toy', 'game'] },
        { emoji: '🎱', tags: ['billiards', 'pool', 'game'] },
        { emoji: '🔮', tags: ['crystal ball', 'fortune', 'mystic'] },
        { emoji: '🪄', tags: ['magic wand', 'magic', 'trick'] },
        { emoji: '🎮', tags: ['video game', 'controller', 'play'] },
        { emoji: '🕹️', tags: ['joystick', 'video game', 'play'] },
        { emoji: '🎰', tags: ['slot machine', 'casino', 'gamble'] },
        { emoji: '🎲', tags: ['dice', 'game', 'play'] },
        { emoji: '🧩', tags: ['puzzle', 'piece', 'game'] },
        { emoji: '🧸', tags: ['teddy bear', 'toy', 'cute'] },
        { emoji: '🪅', tags: ['pinata', 'party', 'celebrate'] },
        { emoji: '🪩', tags: ['disco ball', 'party', 'music'] },
        { emoji: '🪆', tags: ['nesting dolls', 'russia', 'toy'] }  
        ],
    
    travel: [
        { emoji: '🌍', tags: ['earth', 'world', 'continent'] },
        { emoji: '🌎', tags: ['earth', 'world', 'americas'] },
        { emoji: '🌏', tags: ['earth', 'world', 'asia'] },
        { emoji: '🌐', tags: ['globe', 'internet', 'world'] },
        { emoji: '🗺️', tags: ['map', 'world', 'explore'] },
        { emoji: '🗾', tags: ['map', 'japan', 'asia'] },
        { emoji: '🧭', tags: ['compass', 'direction', 'navigation'] },
        { emoji: '🏔️', tags: ['mountain', 'snow', 'peak'] },
        { emoji: '⛰️', tags: ['mountain', 'hill', 'peak'] },
        { emoji: '🌋', tags: ['volcano', 'eruption', 'lava'] },
        { emoji: '🗻', tags: ['mount fuji', 'japan', 'mountain'] },
        { emoji: '🏕️', tags: ['camping', 'tent', 'outdoors'] },
        { emoji: '🏖️', tags: ['beach', 'umbrella', 'vacation'] },
        { emoji: '🏜️', tags: ['desert', 'sand', 'hot'] },
        { emoji: '🏝️', tags: ['island', 'beach', 'vacation'] },
        { emoji: '🏞️', tags: ['national park', 'outdoors', 'scenic'] },
        { emoji: '🏟️', tags: ['stadium', 'sports', 'arena'] },
        { emoji: '🏛️', tags: ['building', 'government', 'monument'] },
        { emoji: '🏗️', tags: ['construction', 'building', 'build'] },
        { emoji: '🧱', tags: ['bricks', 'construction', 'build'] },
        { emoji: '🪨', tags: ['rock', 'stone', 'boulder'] },
        { emoji: '🪵', tags: ['wood', 'log', 'forest'] },
        { emoji: '🛖', tags: ['hut', 'building', 'primitive'] },
        { emoji: '🏘️', tags: ['houses', 'neighborhood', 'community'] },
        { emoji: '🏚️', tags: ['abandoned house', 'building', 'ruins'] },
        { emoji: '🏠', tags: ['house', 'home', 'building'] },
        { emoji: '🏡', tags: ['house', 'garden', 'home'] },
        { emoji: '🏢', tags: ['office building', 'work', 'city'] },
        { emoji: '🏣', tags: ['post office', 'building', 'mail'] },
        { emoji: '🏤', tags: ['post office', 'building', 'government'] },
        { emoji: '🏥', tags: ['hospital', 'medical', 'building'] },
        { emoji: '🏦', tags: ['bank', 'building', 'money'] },
        { emoji: '🏨', tags: ['hotel', 'building', 'vacation'] },
        { emoji: '🏩', tags: ['love hotel', 'building', 'romance'] },
        { emoji: '🏪', tags: ['convenience store', 'building', 'shop'] },
        { emoji: '🏫', tags: ['school', 'building', 'education'] },
        { emoji: '🏬', tags: ['department store', 'shopping', 'building'] },
        { emoji: '🏭', tags: ['factory', 'building', 'industry'] },
        { emoji: '🏯', tags: ['castle', 'japan', 'building'] },
        { emoji: '🏰', tags: ['castle', 'building', 'fantasy'] },
        { emoji: '💒', tags: ['wedding', 'chapel', 'building'] },
        { emoji: '🗼', tags: ['tokyo tower', 'japan', 'building'] },
        { emoji: '🗽', tags: ['statue of liberty', 'new york', 'monument'] },
        { emoji: '⛪', tags: ['church', 'building', 'religion'] },
        { emoji: '🕌', tags: ['mosque', 'religion', 'building'] },
        { emoji: '🛕', tags: ['hindu temple', 'religion', 'building'] },
        { emoji: '🕍', tags: ['synagogue', 'religion', 'building'] },
        { emoji: '⛩️', tags: ['shinto shrine', 'religion', 'japan'] },
        { emoji: '🕋', tags: ['kaaba', 'islam', 'mecca'] },
        { emoji: '⛲', tags: ['fountain', 'water', 'park'] },
        { emoji: '⛺', tags: ['tent', 'camping', 'outdoors'] },
        { emoji: '🌁', tags: ['foggy', 'bridge', 'weather'] },
        { emoji: '🌃', tags: ['night city', 'city', 'skyline'] } 
    ],
    
    objects: [
        { emoji: '👓', tags: ['glasses', 'eyewear', 'vision'] },
        { emoji: '🕶️', tags: ['sunglasses', 'cool', 'fashion'] },
        { emoji: '🥽', tags: ['goggles', 'protection', 'sports'] },
        { emoji: '🥼', tags: ['lab coat', 'science', 'medical'] },
        { emoji: '🦺', tags: ['safety vest', 'protection', 'work'] },
        { emoji: '👔', tags: ['tie', 'shirt', 'formal'] },
        { emoji: '👕', tags: ['t-shirt', 'clothing', 'casual'] },
        { emoji: '👖', tags: ['jeans', 'clothing', 'casual'] },
        { emoji: '🧣', tags: ['scarf', 'warm', 'clothing'] },
        { emoji: '🧤', tags: ['gloves', 'warm', 'clothing'] },
        { emoji: '🧥', tags: ['coat', 'warm', 'clothing'] },
        { emoji: '🧦', tags: ['socks', 'clothing', 'foot'] },
        { emoji: '👗', tags: ['dress', 'clothing', 'fashion'] },
        { emoji: '👘', tags: ['kimono', 'clothing', 'japan'] },
        { emoji: '🥻', tags: ['sari', 'clothing', 'india'] },
        { emoji: '🩱', tags: ['one-piece swimsuit', 'clothing', 'swim'] },
        { emoji: '🩲', tags: ['briefs', 'clothing', 'swim'] },
        { emoji: '🩳', tags: ['shorts', 'clothing', 'swim'] },
        { emoji: '👙', tags: ['bikini', 'clothing', 'swim'] },
        { emoji: '👚', tags: ['blouse', 'clothing', 'fashion'] },
        { emoji: '🪭', tags: ['fan', 'accessory', 'cool'] },
        { emoji: '👛', tags: ['purse', 'bag', 'accessory'] },
        { emoji: '👜', tags: ['handbag', 'bag', 'accessory'] },
        { emoji: '👝', tags: ['clutch', 'bag', 'accessory'] },
        { emoji: '🛍️', tags: ['shopping bag', 'bag', 'purchase'] },
        { emoji: '🎒', tags: ['backpack', 'bag', 'school'] },
        { emoji: '🩴', tags: ['flip flop', 'footwear', 'sandals'] },
        { emoji: '👞', tags: ['shoe', 'footwear', 'formal'] },
        { emoji: '👟', tags: ['sneaker', 'footwear', 'casual'] },
        { emoji: '🥾', tags: ['hiking boot', 'footwear', 'adventure'] },
        { emoji: '🥿', tags: ['flat shoe', 'footwear', 'fashion'] },
        { emoji: '👠', tags: ['high heel', 'footwear', 'fashion'] },
        { emoji: '👡', tags: ['sandal', 'footwear', 'fashion'] },
        { emoji: '🩰', tags: ['ballet shoes', 'footwear', 'dance'] },
        { emoji: '👢', tags: ['boot', 'footwear', 'fashion'] }
    ],
    
    symbols: [
        { emoji: '🏧', tags: ['atm', 'money', 'bank'] },
        { emoji: '🚮', tags: ['litter', 'trash', 'bin'] },
        { emoji: '🚰', tags: ['potable water', 'drink', 'fountain'] },
        { emoji: '♿', tags: ['wheelchair', 'accessibility', 'disabled'] },
        { emoji: '🚹', tags: ['men', 'restroom', 'male'] },
        { emoji: '🚺', tags: ['women', 'restroom', 'female'] },
        { emoji: '🚻', tags: ['restroom', 'toilet', 'public'] },
        { emoji: '🚼', tags: ['baby', 'restroom', 'changing'] },
        { emoji: '🚾', tags: ['wc', 'restroom', 'bathroom'] },
        { emoji: '🛂', tags: ['passport control', 'travel', 'border'] },
        { emoji: '🛃', tags: ['customs', 'travel', 'border'] },
        { emoji: '🛄', tags: ['baggage claim', 'travel', 'luggage'] },
        { emoji: '🛅', tags: ['left luggage', 'travel', 'luggage'] },
        { emoji: '🗣️', tags: ['speaking', 'talk', 'speech'] },
        { emoji: '👤', tags: ['person', 'user', 'profile'] },
        { emoji: '👥', tags: ['people', 'friends', 'group'] },
        { emoji: '🫂', tags: ['hug', 'friends', 'comfort'] },
        { emoji: '👣', tags: ['footprints', 'feet', 'steps'] },
        { emoji: '⚠️', tags: ['warning', 'danger', 'caution'] },
        { emoji: '🚸', tags: ['children crossing', 'school', 'caution'] },
        { emoji: '⛔', tags: ['no entry', 'stop', 'prohibited'] },
        { emoji: '🚫', tags: ['no entry', 'forbidden', 'stop'] },
        { emoji: '🚳', tags: ['no bicycles', 'prohibited', 'stop'] },
        { emoji: '🚭', tags: ['no smoking', 'prohibited', 'stop'] },
        { emoji: '🚯', tags: ['no littering', 'prohibited', 'stop'] },
        { emoji: '🚱', tags: ['no drinking water', 'prohibited', 'stop'] },
        { emoji: '🚷', tags: ['no pedestrians', 'prohibited', 'stop'] },
        { emoji: '📵', tags: ['no mobile phones', 'prohibited', 'stop'] },
        { emoji: '🔞', tags: ['no under 18', 'adult', 'prohibited'] },
        { emoji: '☢️', tags: ['radioactive', 'danger', 'hazard'] },
        { emoji: '☣️', tags: ['biohazard', 'danger', 'hazard'] },
        { emoji: '⬆️', tags: ['up', 'arrow', 'north'] },
        { emoji: '↗️', tags: ['up-right', 'arrow', 'direction'] },
        { emoji: '➡️', tags: ['right', 'arrow', 'east'] },
        { emoji: '↘️', tags: ['down-right', 'arrow', 'direction'] },
        { emoji: '⬇️', tags: ['down', 'arrow', 'south'] },
        { emoji: '↙️', tags: ['down-left', 'arrow', 'direction'] },
        { emoji: '⬅️', tags: ['left', 'arrow', 'west'] },
        { emoji: '↖️', tags: ['up-left', 'arrow', 'direction'] },
        { emoji: '↕️', tags: ['up-down', 'arrow', 'vertical'] },
        { emoji: '↔️', tags: ['left-right', 'arrow', 'horizontal'] },
        { emoji: '↩️', tags: ['right arrow curving left', 'back'] },
        { emoji: '↪️', tags: ['left arrow curving right', 'forward'] },
        { emoji: '⤴️', tags: ['up arrow curving right', 'forward'] },
        { emoji: '⤵️', tags: ['down arrow curving right', 'back'] },
        { emoji: '🔃', tags: ['clockwise arrows', 'refresh', 'sync'] },
        { emoji: '🔄', tags: ['counterclockwise arrows', 'refresh', 'sync'] },
        { emoji: '🔙', tags: ['back', 'arrow', 'return'] },
        { emoji: '🔚', tags: ['end', 'arrow', 'finish'] },
        { emoji: '🔛', tags: ['on', 'arrow', 'toggle'] },
        { emoji: '🔜', tags: ['soon', 'arrow', 'forward'] },
        { emoji: '🔝', tags: ['top', 'arrow', 'up'] }
    ]        
};
